version: '3'
services:
  web:
    build: .
    environment:
      PYTHONPATH: /app/.heroku/opencv/lib/python2.7/site-packages
      PORT: ${PORT:-3000}
    volumes:
      - .:/greenthumb-image-api
    ports:
      - "3033:${PORT:-3000}"
