version: '3'
services:
  web:
    build: .
    command: ./greenthumbor.sh
    volumes:
      - .:/greenthumb-image-api
      - ../thumbor-greenthumb-filter:/thumbor-greenthumb-filter
    ports:
      - "3030:3030"
